# Generated by Django 4.2.4 on 2023-08-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('particular', models.BooleanField(default=False)),
                ('juzgado', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('hora_registro', models.TimeField()),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('hora_limite', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('respuesta', models.FileField(blank=True, null=True, upload_to='respuestas')),
                ('clave', models.CharField(blank=True, max_length=100, null=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respuestas.solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respuestas.solicitud')),
            ],
        ),
    ]
